README.md

Update readme within branch

---

code/game/turfs/simulated/wall_types.dm

Sanitized -  Snow walls!

---

nano/templates/autodoc_capitalism.tmpl

Autodoc fix from sojourn-station, had to be manually added because github.

Autodoc fix from sojourn-station (unable to PR for some reason)

---

code/datums/datum_click_handlers.dm
code/game/verbs/who.dm
code/modules/projectiles/ammunition.dm
code/modules/projectiles/gun.dm
code/modules/projectiles/guns/projectile/automatic.dm
code/modules/surgery/autodoc.dm

Ported the fixes part of Trilby's Gun fix port + QoL ports + misc fixes PR. Compiles successfully.
Original PR: https://github.com/sojourn-13/sojourn-station/pull/5971/commits
Fixes Commit: https://github.com/sojourn-13/sojourn-station/pull/5971/commits/0830b17025444153d207e7fa1f40586aed3b4ed2

Ported fixes from sojourn-station

---

code/game/objects/items/weapons/tools/_tools.dm
code/modules/mob/living/living_defense.dm
code/modules/paperwork/folders.dm

Fixes two list index out of bounds errors (living_defence.dm and folders.dm) and one divide by zero (_tools.dm) error.

List index out of bounds and divide by zero patches

---

code/controllers/subsystems/statpanel.dm
code/modules/tgui/tgui.dm

Adds sanity checks to two files. There's also the merge branch commit that is here for some reason (thanks github), but it doesn't change anything so it should be harmless.

More sanity checks

---

code/__HELPERS/unsorted.dm
code/modules/mob/living/carbon/carbon.dm
code/modules/organs/organ.dm

Sanity Checks

---

code/game/machinery/camera/presets.dm
code/modules/projectiles/projectile/bullettypes.dm

Two sanity checks, fixes these errors:
```Runtime in code/game/machinery/camera/presets.dm,144: Cannot read null.upgrades```
```Runtime in code/modules/projectiles/projectile/bullettypes.dm,886: Cannot execute null.trans to mob().```

Cfw pre merge

---

code/modules/trade/datums/_trade_station.dm

Attempts to fix ```Runtime in code/modules/trade/datums/_trade_station.dm,248: list index out of bounds```

Test fix for list index out of bounds in _trade_station.dm

---

code/modules/client/preference_setup/global/preferences.dm
code/modules/mob/floating_say.dm
code/modules/mob/living/say.dm
sojourn-iskhod.dme

It works, but it needs to be enabled by people in preferences (or it did for me at least).

Added Runechat (Lightly Tested)

---

code/modules/trade/datums/_trade_station.dm

Reverts epic-new-soj-thing/Sojourn-Iskhod#33
- Test fix for cargo, attempting to isolate the issue. Re-do this PR if it's not the issue.
Auth'd by CFW

Revert "Test fix for list index out of bounds in _trade_station.dm"

---

code/game/objects/items/devices/organ_module/simple.dm

Fixes:
Runtime in code/game/objects/items/devices/organ_module/simple.dm,50: Cannot read null.loc

Sanity Check for simple.dm

---

code/datums/mob_stats.dm
code/game/machinery/vendor/recycle_vendor.dm
code/modules/materials/material_sheets.dm
code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm
code/modules/modular_computers/file_system/reports/crew_record.dm
code/modules/modular_computers/hardware/scanners/scanner_medical.dm
code/modules/power/hydrogen_generator.dm
code/modules/projectiles/dynamic_cursor.dm
code/modules/research/xenoarchaeology/finds/finds.dm

Fixes these runtimes:
Runtime in code/modules/modular_computers/file_system/reports/crew_record.dm,58: Cannot read null.account_number
Runtime in code/modules/research/xenoarchaeology/finds/finds.dm,314: Cannot modify null.price_tag.
Runtime in code/modules/modular_computers/hardware/scanners/scanner_medical.dm,15: Cannot execute null.nano ui interact().
Runtime in code/modules/mob/living/carbon/superior_animal/giant_spider/attack.dm,42: Cannot execute null.Enter().
Runtime in code/modules/projectiles/dynamic_cursor.dm,28: Cannot execute null.remove cursor().
Runtime in code/datums/mob_stats.dm,85: Cannot read null.name
Runtime in code/game/machinery/vendor/recycle_vendor.dm,194: Cannot read null.name
Runtime in code/modules/materials/material_sheets.dm,87: Cannot read null.name
Runtime …

Sanity Checks and Fixes a Typo

---

code/modules/genetics/machinery/genetics_cloner.dm
code/modules/mob/living/simple_animal/hostile/carp.dm

Sync with pre-merge

---

code/modules/lighting/lighting_overlay.dm
code/modules/lighting/lighting_source.dm

Fixed longstanding lighting runtimes and, potentially, a lighting CM crash, Done by Ryuu

Ryuu lighting

---

code/ZAS/Controller.dm
code/__DEFINES/_compile_options.dm
code/__HELPERS/game.dm
code/controllers/evacuation/evacuation.dm
code/controllers/subsystems/xenoarch.dm
code/game/area/Space Station 13 areas.dm
code/game/gamemodes/endgame/supermatter_cascade/universe.dm
code/modules/admin/verbs/atmosdebug.dm
code/modules/admin/verbs/check_customitem_activity.dm
code/modules/dungeons/procedural/jp_dungeon_gen.dm
code/modules/hydroponics/seed_controller.dm
code/modules/hydroponics/spreading/spreading.dm
code/modules/maps/map_template.dm
code/modules/maps/tg/map_template.dm
code/modules/mob/living/carbon/alien/life.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/mob/living/carbon/slime/life.dm
code/modules/mob/living/life.dm
code/modules/mob/living/silicon/robot/life.dm
code/modules/mob/observer/freelook/chunk.dm
code/modules/multiz/turf_icon.dm
code/modules/research/xenoarchaeology/geosample.dm
code/modules/research/xenoarchaeology/tools/tools_anoscanner.dm
code/modules/research/xenoarchaeology/tools/tools_locater.dm
code/modules/shieldgen/shield_gen.dm

Removes "set backround" from the code as it appears to be doing nothing
- Removed set background

Remove set background

---

code/__DEFINES/maths.dm
code/__DEFINES/movement.dm
code/controllers/subsystems/movement/movement_types.dm
code/modules/client/edge_sliding/move_loop.dm
code/modules/mob/login.dm
code/modules/mob/mob.dm

- Enables diagonal movement
- Adds some movement delay when moving diagonally
Initial creation by Trilby: https://github.com/sojourn-13/sojourn-station/pull/5983

Diagonal Movement Patch

---

code/game/machinery/computer/computer.dm
code/game/objects/effects/portals.dm
code/game/objects/items/weapons/grenades/grenade.dm
code/modules/mob/mob_grab.dm
code/modules/organs/external/damage.dm
code/modules/random_map/drop/supply.dm
maps/_DeepForest/map/_Deep_Forest.dmm
maps/__Nadezhda/area/_Nadezhda_areas.dm

- Plethora of null.x runtime fixes
- Hotfix for Safehouse areas

HotFixes 25.04.30

---

code/game/machinery/atmoalter/scrubber.dm

- Sanity check/yggdrasil hotfix

Yggdrasil Hotfix

---

code/__DEFINES/_macros.dm
code/__DEFINES/html_assistant.dm
code/__DEFINES/maths.dm
code/__HELPERS/game.dm
code/__HELPERS/unsorted.dm
code/controllers/hooks.dm
code/game/machinery/atmoalter/area_atmos_computer.dm
code/game/machinery/computer/aifixer.dm
code/modules/admin/admin.dm
code/modules/asset_cache/asset_cache_client.dm
code/modules/hydroponics/seed_storage.dm
code/modules/overmap/ships/ship.dm
code/modules/paperwork/faxmachine.dm
code/modules/paperwork/photocopier.dm
sojourn-iskhod.dme

Basically port https://github.com/Monkestation/Monkestation2.0/pull/5861 to fix our UI issues in 516
- Fix compiling issues in 516.
- Fix UI issues in 516. A few probably got through the cracks, so report them when you see them.

Fix 516 UI errors

---

code/controllers/configuration.dm
code/game/machinery/doors/airlock.dm
code/modules/reagents/reagent_containers/glass.dm

Scrambled updates from CFW work branch
- Increases character slots from 10 to 20
- Removes pen-scribbling sound from glass bottle creation in chem-masters (Original edit by du-top)
- Hotfixes psionic tool duplication glitch

25.05.08 - CFW

---

code/controllers/configuration.dm
code/datums/perks/backgrounds.dm
code/game/objects/items/devices/organ_module/passive/sanity.dm
code/modules/sanity/breakdowns.dm
code/modules/sanity/sanity_mob.dm

Scheduled edits by CFW
- Enables automatic server restarts on empty server/AFK lobby during round starts
- Disables negative sanity breakdows

CFW - 25.05.09

---

code/modules/turbolift/turbolift_console.dm

Previous fix didn't fix the internal console, only the external call buttons.

hopefully fixes elevator error, requires testing

---

maps/__Nadezhda/map/_Nadezhda_Colony.dmm
nano/templates/rdconsole.tmpl

CFW work - 25.05.10
- Removes the ability to lock the RnD console as requested by MsRandylicious
- Replaces the random cells in Research with two Large and two Medium Omega-Geyser cells

Cfw work branch

---

code/datums/perks/backgrounds.dm
code/datums/perks/racial.dm
code/modules/mob/language/outsider.dm

- Makes Kriosan a Restricted Language, can only be selected by the relevant species.
- Makes Kriosan a written language, to signify cultural resurgence in new lore.
- Changes syllables of Krisoan to be more doglike.

Kriosan Language Changes

---

code/datums/craft/gun_parts.dm
code/game/machinery/vendor/recycle_vendor.dm
code/modules/projectiles/ammunition/boxes.dm

Weekly merge before scheduled maintenance
- Fixes the recycling vending machine to prevent psionic tool duplication
- Fixes the sprites for the .35 firearm barrels
- Fixes the sprites and description for 10x24mm caseless ammunition

Scheduled CFW work merge

---

code/modules/clothing/spacesuits/rig/modules/storage.dm

Fixes inverted variable on hardsuit storage

fixes very minor error

---

code/__DEFINES/jobs.dm
code/datums/outfits/jobs/science.dm
code/game/jobs/department.dm
code/game/jobs/job/science.dm
code/game/jobs/jobs.dm
code/modules/multiz/map_data.dm
maps/__Nadezhda/map/_Nadezhda_Colony.dmm

Science Interns (done via template of Trilby's PR for upstream:  https://github.com/sojourn-13/sojourn-station/pull/5513/commits )
- Introduces Science and Robotics Intern roles
- Restricts Scientist and Roboticist roles to 4+ hours of playtime

Science Interns

---

maps/__Nadezhda/map/_Nadezhda_Colony.dmm

Map tweaks, rebuilt by hand based on PR #88 by Dr. Farson: https://github.com/epic-new-soj-thing/Sojourn-Iskhod/pull/88
- Removes oil stains from the colony
- Rebuilds Anti Matter engine chamber
- Adds a built bullet fabricator to guild workshop
- Replaces guild glass on lower level with r-glass
- Adds warning signs decoration to the Guild
- Removes shield generator, renames it's SMES units in RCON
- Replaces one Large Omega-Cell in SI with a Small one

Minor/Guild Map Tweaks

---

code/game/objects/structures/crates_lockers/closets/utility_closets.dm
code/modules/client/preference_setup/loadout/lists/clothing.dm
code/modules/client/preference_setup/loadout/lists/gloves.dm
code/modules/client/preference_setup/loadout/lists/suits.dm
code/modules/clothing/suits/miscellaneous.dm

Various Misc Tweaks
- Adds pockets to fancy outer suits just like jackets
- Adjusts loadout glove costs to 0 points (same as boots)
- Adjusts loadout gasmask costs to 1 point
- Adjusts loadout bunny suit cost to 0 points (same as other suits)
- Adds a pair of thick gloves to regular fire-closet (same as wall firecloset)

work-branch-merge-26.05.25

---

code/controllers/configuration.dm
code/game/jobs/job/blackshield.dm

CFW work branch things
- Sets the respawn timer to 5 minutes
- Allows SI synthetics to be Blackshield Cadets to unlock the Corpsman role

Work Branch Emergency Merge

---

code/modules/mob/living/say.dm

Mice can no longer speak to people using Runechat
- Removed ability for mice to speak human languages in Runechat

Removes ability for mice to speak human using Runechat

---

code/game/machinery/vendor/weapon_kit_vendors.dm
code/game/objects/items/weapons/storage/marshal_kits.dm
code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
code/modules/projectiles/guns/energy/pulse/glock.dm

Gives CRO back the hydrogen-plasma sword.
Renames Galaxy to SI-NM instead of SI-HG.
Re-adds the Galaxy to the WO, removing it from CRO.

Gives WO back the Galaxy

---

code/game/objects/items/musictapes.dm
code/modules/core_implant/cruciform/machinery/eotp.dm
code/modules/mob/animations.dm
code/modules/mob/living/simple_animal/hostile/dino.dm
code/modules/multiz/structures.dm
code/modules/organs/body_modifications.dm
code/modules/paperwork/folders.dm
code/modules/projectiles/guns/_projectile.dm

Fixes various runtimes (listed below).
Credit to AlexMorgan3817 for the Music Tape fix (https://github.com/discordia-space/CEV-Eris/pull/6471)
- Fixed multiple runtimes
Runtime in code/modules/multiz/structures.dm,124: Cannot read null.loc
Runtime in code/modules/organs/body_modifications.dm,61: Cannot execute null.get modification().
Runtime in code/modules/projectiles/guns/_projectile.dm,450: Cannot read null.type
Runtime in code/modules/mob/animations.dm,322: Cannot modify null.eye.
Runtime in code/modules/core_implant/cruciform/machinery/eotp.dm,203: Cannot read null.power_regen
Runtime in code/modules/mob/living/simple_animal/hostile/dino.dm,71: Cannot read null.department_flag
Runtime in code/modules/paperwork/folders.dm,77: list index out of bounds
Runtime in …

Runtime Fixes

---

code/modules/clothing/suits/armor.dm
code/modules/cooking_with_jane/recipes/recipe.dm

CFW Work Branch Merge
- Removes Warrant Officer plate carrier slowdown, as requested by John-Guild
- Removes SolFed plate carrier slowdown, as it is essentially a copy of WO plate carrier
- Fixes Birthday Cake recipe (replaces cake-hat requirement by 30u glaze)

Scheduled CFW branch merge

---

code/controllers/admin.dm
code/controllers/subsystems/ticker.dm
code/modules/admin/verbs/adminhelp.dm
code/modules/admin/verbs/adminpm.dm

- Adds auto restart, coded and implemented by [Pavelgon4ik](https://github.com/Pavelgon4ik)
- Edits admin.dm, adminpm.dm, and adminhelp.dm to forward stuff to the bot.

Auto Restart + Better Ahelp Forwards

---

code/game/machinery/tesla_turret.dm
code/modules/cooking_with_jane/cooking_appliances/cooking_circuits.dm
code/modules/genetics/machinery/advanced_grinder.dm
code/modules/genetics/machinery/genetics_cloner.dm
code/modules/genetics/machinery/genetics_designs.dm
code/modules/genetics/machinery/genetics_items.dm
code/modules/paperwork/pen.dm
code/modules/psionics/psionic_items/psi_armor.dm
code/modules/research/designs/psionic.dm

Replaced Blue Ink with Soteria

Replaced Blue Ink with Soteria

---

code/modules/ameridian/ameridian_crystal.dm
code/modules/ameridian/ameridian_spire.dm

Fix a couple of issues that prevented ameridian from spreading & growing correctly.
\- Fix a couple of issues that prevented ameridian from spreading & growing correctly.

Fix ameridian growth & spread.

---

code/modules/client/preference_setup/loadout/lists/fluff.dm
code/modules/reagents/reagents/food-Drinks.dm

adds me fluf item, a hydrogen plasma sword saya
(sword not included)

adds me fluf item

---

code/game/machinery/alarm.dm

alarms on!

---

code/game/machinery/nuclear_bomb.dm
nano/templates/nuclear_bomb.tmpl

last fix I promise

---

code/game/machinery/nuclear_bomb.dm

minor fixes

---

code/game/jobs/job/blackshield.dm
code/game/jobs/job/church.dm
code/game/jobs/job/engineering.dm
code/game/jobs/job/guild.dm
code/game/jobs/job/medical.dm
code/game/jobs/job/prospector.dm
code/game/jobs/job/science.dm
code/game/jobs/job/security.dm
code/game/machinery/alarm.dm
nano/templates/nuclear_bomb.tmpl

anchor fixes and air alarm fixes

---

code/game/machinery/nuclear_bomb.dm

Nuclear!!!!

---

code/game/machinery/nuclear_bomb.dm
code/modules/client/preference_setup/loadout/lists/fluff.dm

cloak add + sound fix

---

code/datums/craft/recipes/soteria.dm
code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm

Allows Gauze to be injected. Adds reagents to church gauze.

---

code/modules/projectiles/projectile/special.dm

nerf sad :(

---

code/game/objects/items/weapons/weaponry.dm
code/modules/client/preference_setup/loadout/lists/fluff.dm
code/modules/projectiles/guns/launcher/rocket.dm
code/modules/research/nodes/combat.dm

Floof's Cloak

---

code/game/mecha/combat/durand.dm
code/game/mecha/working/hoverpod.dm
code/modules/projectiles/guns/launcher/rocket.dm
code/modules/projectiles/projectile/special.dm
code/modules/research/designs/weapon.dm
code/modules/research/nodes/combat.dm

many SPEAR balance changes

---

code/modules/projectiles/guns/launcher/rocket.dm
maps/__Nadezhda/map/_Nadezhda_Colony.dmm

adds turrets to nuke room

---

code/modules/projectiles/guns/projectile/other/RPG.dm

Renames the RPG to RPG-7

---

code/controllers/configuration.dm
code/game/verbs/who.dm

admin-only-who

---

code/datums/perks/backgrounds.dm
code/datums/perks/cooldown.dm
code/datums/perks/imprinter_perks.dm
code/datums/perks/job.dm
code/datums/perks/nanite_powers.dm
code/datums/perks/nanogate.dm
code/datums/perks/nepotism.dm
code/datums/perks/oddity.dm
code/datums/perks/perk.dm
code/datums/perks/psionic.dm
code/datums/perks/racial.dm
code/datums/perks/special.dm
code/game/jobs/job/medical.dm
code/game/machinery/adv_med.dm
code/game/objects/items/devices/scanners/health.dm
code/game/objects/items/weapons/storage/boxes.dm
code/modules/mob/living/carbon/brain/brain_item.dm
code/modules/mob/living/carbon/human/human_powers.dm
code/modules/mob/living/carbon/human/life.dm
code/modules/organs/external/dismemberment.dm
code/modules/reagents/reagent_containers/hypospray.dm
modular_sojourn/Borers/__ADMIN SHIT/antagonist.dm
modular_sojourn/Borers/borer.dm
modular_sojourn/Borers/borer_powers.dm

re-implements borer code

---

code/modules/organs/external/damage.dm

Fixed brute_mod_perk and burn_mod_perk not doing anything

Fix damage mods

---

code/modules/core_implant/cruciform/machinery/onlooker.dm
code/modules/core_implant/cruciform/rituals/construction.dm

Nullifier spellcheck

---

code/modules/sanity/sanity_mob.dm

quickly spitting PR out teehee, removes anomalies vanishing after use on oddity
on the can

revert anomaly removal on use

---

code/game/objects/structures/crates_lockers/closets/secure/medical.dm

Adds Hypersleeper to CBO locker again.

---

code/modules/modular_computers/file_system/programs/research/cyborg_remote.dm
nano/templates/robot_control.tmpl

Adds GPS Coords to Cyborg Console

---

code/game/objects/items/weapons/emp_mine.dm

fixes the misspell in the one star EMP mine description

spell cheg

---

tools/ci/install_byond.sh

github changes

---

code/datums/setup_option/core_implants.dm

gives the RD access to the cultured tumor, thats it
you're welcome

gives the RD cancer

---

code/game/machinery/vendor/one_star_vending.dm
code/game/objects/items/stacks/medical_stacks/bruise_pack_stack.dm
code/game/objects/items/stacks/medical_stacks/ointment_stacks.dm
code/modules/projectiles/ammunition/bullets.dm

adds greyson multi-kits to vendors, Fixes SABUL, fixes SI gauze

---

code/game/objects/items/weapons/autolathe_disk/greyson_excelsior_disks.dm

fixes greyson disk cost

---

code/game/objects/items/devices/scanners/health.dm

fixes greyson health analyser

---

code/datums/perks/job.dm
code/modules/projectiles/guns/projectile/boltgun.dm

it.. ports the PR that makes the boltgun training perk togglable myeah
https://github.com/sojourn-13/sojourn-station/pull/6067
tested on local, works fine
ports https://github.com/sojourn-13/sojourn-station/pull/6067

ports trilby making blackshield boltgun perk togglable

---

code/modules/mob/living/carbon/superior_animal/roach/roach_chems.dm

ports https://github.com/sojourn-13/sojourn-station/pull/6073
removes a single character in code

ports trilby fixing kaiser and fuhrer roach revival

---

code/game/objects/items/oddities_faction.dm
code/modules/reagents/reagents/drugs.dm

Rebalances the Molitor-Rieder Enricher to produce Nanoblood instead of O- at a lesser rate.
Changes the colour of nanoblood.

rebalances cbo blood item

---

code/datums/autolathe/basic_stuff.dm
code/game/objects/items/weapons/autolathe_disk/lonestar_disks.dm

Add Caution Wet Floor Sign to LSS Janitor Disk
requested by @AMcilraith
makes Wet Floor Sign printable from janitor disc
add datum to autolathe basic 
add design to LSS Janitor disc

Add Caution Wet Floor Sign to LSS Janitor Disk

---

code/game/objects/items/weapons/caution.dm
maps/__Nadezhda/area/_Nadezhda_areas.dm

Fixes a bruh moment from the "Servist" substation
Didnt touch the area line itself which is also labeled servist as to not fuck up any DMM compiling or whatever.
fixes _nadezhda_area.dm spelling to Service substation

Servist spelling fix

---

code/modules/client/border_control_database.dm

comments out some things

---

code/modules/clothing/spacesuits/rig/suits/station.dm

major rigsuit bugfix

---

code/__HELPERS/_logging.dm
code/__HELPERS/text.dm
code/game/machinery/newscaster.dm
code/game/world.dm
code/modules/admin/admin.dm
code/modules/admin/verbs/randomverbs.dm
code/modules/economy/economy_misc.dm

newscaster should work now

---

maps/__Nadezhda/map/_Nadezhda_Colony.dmm

https://github.com/user-attachments/assets/b0f054ff-5beb-451c-897b-6bde0b0a64ec

Command Armory update
